-- WardenOS file list, read by install.lua. Paths are relative to src/ and to / on the computer.
-- Add every new OS file here (tests/check.py verifies this list matches src/).
-- Bump version together with src/os/config.lua and src/os/drone/agent.lua.
return {
  version = "1.6.0",
  files = {
    "startup.lua",
    "os/config.lua",
    "os/boot.lua",
    "os/kernel.lua",
    "os/lib/bigfont.lua",
    "os/lib/claude.lua",
    "os/lib/claudetools.lua",
    "os/lib/json.lua",
    "os/lib/log.lua",
    "os/lib/login.lua",
    "os/lib/map.lua",
    "os/lib/mineview.lua",
    "os/lib/pocketserver.lua",
    "os/lib/screen.lua",
    "os/lib/settings.lua",
    "os/lib/sha256.lua",
    "os/lib/templates.lua",
    "os/lib/world.lua",
    "os/apps/about.lua",
    "os/apps/claude.lua",
    "os/apps/dashboard.lua",
    "os/apps/drones.lua",
    "os/apps/edit.lua",
    "os/apps/files.lua",
    "os/apps/lua.lua",
    "os/apps/map.lua",
    "os/apps/mineview.lua",
    "os/apps/monitoring.lua",
    "os/apps/peripherals.lua",
    "os/apps/settings.lua",
    "os/apps/terminal.lua",
    "os/apps/todo.lua",
    "os/bin/btop.lua",
    "os/bin/neofetch.lua",
    "os/drone/agent.lua",
    "os/drone/startup.lua",
    "os/pocket/claudecore.lua",
    "os/pocket/main.lua",
    "os/pocket/startup.lua",
  },
  -- what a turtle gets (os/drone/startup.lua becomes /startup.lua)
  drone = {
    "os/drone/agent.lua",
    "os/drone/startup.lua",
  },
  -- what an Advanced Pocket Computer gets (os/pocket/startup.lua becomes /startup.lua)
  pocket = {
    "os/bin/btop.lua",
    "os/bin/neofetch.lua",
    "os/config.lua",
    "os/lib/claude.lua",
    "os/lib/claudetools.lua",
    "os/lib/json.lua",
    "os/lib/templates.lua",
    "os/pocket/claudecore.lua",
    "os/pocket/main.lua",
    "os/pocket/startup.lua",
  },
}
